version: '1'
services:
  web:
    image: microfinancing:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    platform: linux/amd64
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo


