version: '2'
services:
  web:
    image: odoo:12
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - D:\cub\docker\odoo12:/var/CARE/odoo
      - D:\cub\docker\CARE:/var/CARE/CARE
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo


